# The URL the site will be built for
base_url = "https://xavier2code.site"

# The site title and description; used in feeds by default.
title = "xavier2code"
description = ""

# The default language; used in feeds.
default_language = "en"

# The site theme to use.
theme = "apollo"

# author
author = "xavier"

# When set to "ture", a search index is built from the pages and section
# content for `default_language`
build_search_index = true

generate_feeds = true

compile_sass = true

minify_html = true

# The taxonomies to be rendered for the site and their configuration of the default languages
taxonomies = [{ name = "tags" }]

# Search
[search]
include_title = true
include_description = true
include_path = true
include_content = true
index_format = "elasticlunr_json"

[markdown]
highlight_code = true
highlight_theme = "ayu-light"

[extra]
# Put all your custom variables here
theme = "toggle"
# logo = "site_logo.svg"
favicon = "favicon.png"
fancy_code = true
dynamic_note = true # a note that can be toggled
mathjax = true
mathjax_dollar_inline_enable = true
socials = [
  # Configure socials here
  { name = "email", url = "https://mail.google.com/", icon = "email" },
  { name = "github", url = "https://github.com/xavier2code/", icon = "github" },
  { name = "discord", url = "https://discord.com/", icon = "discord" },
  { name = "reddit", url = "https://www.reddit.com/", icon = "reddit" },
  { name = "x-twitter", url = "https://x.com/", icon = "x-twitter" },
]
menu = [
  # Configure menu bar here
  { name = "/posts", url = "/posts", weight = 1 },
  { name = "/projects", url = "/projects", weight = 2 },
  { name = "/archive", url = "/archive", weight = 3 },
  { name = "/about", url = "/about", weight = 4 },
  { name = "/tags", url = "/tags", weight = 5 },
]

[extra.analytics]
enabled = true

[extra.analytics.goatcounter]
user = "xavier2code"
host = "goatcounter.com" # default= goatcounter.com

[languages]
[languages.zh]
generate_feeds = true
build_search_index = false
taxonomies = [{ name = "tags" }]
