name: Deploy on Push

on:
  push:
    branches:
      - main  # 只在 main 分支 push 时触发

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 设置 SSH
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H gotoxavier.ln.cn >> ~/.ssh/known_hosts

      # 通过 SSH 登录服务器并执行 git pull
      - name: Deploy via SSH
        run: |
          ssh -o StrictHostKeyChecking=no root@gotoxavier.ln.cn "
            cd /home/lighthouse/blog &&
            git fetch origin main &&
            git reset --hard origin/main &&
            git pull origin main
          "
